[package]
name = "ya-test-framework"
version = "0.1.0"
edition = "2021"


[dependencies]
anyhow = "1"
assert_cmd = "2.0"
log = "0.4"
tokio = "1"
url = "2.3"

ya-utils-process = "0.2"

[target.'cfg(target_family = "unix")'.dependencies]
libc="0.2.73"
nix="0.22.0"
