name: SGX Unit Tests

on:
  workflow_dispatch:
    inputs:
      profile:
        description: "Profile (unused right now)"
        required: true
        default: "debug"
  push:
    branches:
      - master
      - payments-dev
      - release/*
      - "**/all-tests"
  pull_request:
    branches:
      - master
      - payments-dev
      - release/*

env:
  rust_stable: 1.71.1

jobs:
  build:
    name: SGX Unit Tests
    env:
      # `-D warnings` means any warnings emitted will cause build to fail
      RUSTFLAGS: "-D warnings -C opt-level=z -C target-cpu=x86-64 -C debuginfo=1"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install Protoc
        uses: arduino/setup-protoc@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          version: "24.x"

      - name: Export protoc env
        id: protoc_env
        run: |
          echo "protoc_bin_path=$(which protoc)" >> $GITHUB_OUTPUT

      - name: Install Rust ${{ env.rust_stable }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.rust_stable }}

      - name: Unit tests for SGX
        working-directory: exe-unit
        env:
          PROTOC: ${{ steps.protoc_env.outputs.protoc_bin_path }}
        run: cargo test --features sgx
